import { describe, it } from "node:test";
import assert from "node:assert/strict";
import { readFileSync, readdirSync, statSync, existsSync } from "node:fs";
import { join, relative, sep } from "node:path";

// `skills/` is what ships in the npm package (package.json "files"); `.agents/skills/`
// is the git-tracked copy this repo dogfoods from. They are two hand-maintained
// copies of the same text, and nothing kept them in sync — a skill edited in one
// tree and not the other drifts silently, and the dogfooded agent then follows
// instructions the product never shipped. `.claude/skills/` is deliberately NOT
// compared: .gitignore excludes it, so it holds zero tracked files and is
// regenerated by `codument update` rather than edited.
const SHIPPED = "skills";
const TRACKED_MIRROR = join(".agents", "skills");

/** Every file under `root`, as paths relative to it, sorted. */
function filesUnder(root: string): string[] {
  const out: string[] = [];
  const walk = (dir: string) => {
    for (const entry of readdirSync(dir).sort()) {
      const abs = join(dir, entry);
      if (statSync(abs).isDirectory()) walk(abs);
      else out.push(relative(root, abs).split(sep).join("/"));
    }
  };
  walk(root);
  return out.sort();
}

describe("shipped skills and their tracked mirror stay identical", () => {
  it("both trees exist and are non-empty", () => {
    // Guards the comparisons below from passing vacuously if a tree is moved or
    // renamed — comparing two empty lists is trivially equal.
    assert.ok(existsSync(SHIPPED), `${SHIPPED}/ must exist`);
    assert.ok(existsSync(TRACKED_MIRROR), `${TRACKED_MIRROR}/ must exist`);
    assert.ok(filesUnder(SHIPPED).length > 0, `${SHIPPED}/ must not be empty`);
  });

  it("contain exactly the same set of files", () => {
    assert.deepEqual(
      filesUnder(TRACKED_MIRROR),
      filesUnder(SHIPPED),
      `${TRACKED_MIRROR}/ and ${SHIPPED}/ hold different files — a skill was added, ` +
        "removed, or renamed in one tree only.",
    );
  });

  it("every file is byte-identical across both trees", () => {
    const drifted: string[] = [];
    for (const rel of filesUnder(SHIPPED)) {
      const a = readFileSync(join(SHIPPED, rel), "utf-8");
      const b = readFileSync(join(TRACKED_MIRROR, rel), "utf-8");
      if (a !== b) drifted.push(rel);
    }
    assert.deepEqual(
      drifted,
      [],
      `edited in one tree only — copy ${SHIPPED}/<path> over ${TRACKED_MIRROR}/<path> ` +
        "(or re-run `codument update`, which rewrites the mirror and leaves a " +
        "SKILL.md.backup to delete): " + drifted.join(", "),
    );
  });
});

// The loop's most frequent question is "which doc owns this file", and roughly a
// dozen places across the shipped guidance answered it by instructing a flat read of
// `docs/.registry.json` — a 72KB file in the field repo, read to learn four lines.
// `context --file --owner` answers it in one line and appeared almost nowhere: the
// expensive door was the documented one.
describe("the guidance routes an ownership question through the cheap door", () => {
  /** Every file whose text is guidance an agent follows, shipped or dogfooded. */
  const GUIDANCE = [
    ...filesUnder(SHIPPED).map((f) => join(SHIPPED, f)),
    ...filesUnder("rules").map((f) => join("rules", f)),
    "AGENTS.md",
    "src/lib/scaffold.ts",
  ];

  it("no instruction says to read the whole registry to find one file's owner", () => {
    // The shape that was wrong, in the words it was written in. A mention of the
    // registry is fine — it IS the map, and registering a source means editing it;
    // what must not survive is an instruction to READ it to answer this question.
    const banned = [
      /[Cc]heck `docs\/\.registry\.json` (?:before and after|and update)/,
      /Read `docs\/\.registry\.json`[,\s]*(?:\n\s*)?(?:and\s+)?[Ff]ind the (?:file )?(?:path|doc)/,
    ];
    const offenders: string[] = [];
    for (const file of GUIDANCE) {
      if (!existsSync(file)) continue;
      const text = readFileSync(file, "utf-8");
      if (banned.some((re) => re.test(text))) offenders.push(file);
    }
    assert.deepEqual(
      offenders,
      [],
      "these send an agent to the whole map for one file's owner — route them through " +
        "`codument context --file <path> --owner`: " + offenders.join(", "),
    );
  });

  it("and the command that answers it is actually named in the guidance", () => {
    const named = GUIDANCE.filter(
      (f) => existsSync(f) && readFileSync(f, "utf-8").includes("--file <path> --owner"),
    );
    assert.ok(
      named.length >= 5,
      `the cheap door has to be documented where the question is asked; found it in ${named.length} file(s)`,
    );
  });
});
