import { describe, it } from "node:test";
import assert from "node:assert/strict";
import { readFileSync, readdirSync, statSync, existsSync } from "node:fs";
import { join, relative, sep } from "node:path";

// `skills/` is what ships in the npm package (package.json "files"); `.agents/skills/`
// is the git-tracked copy this repo dogfoods from. They are two hand-maintained
// copies of the same text, and nothing kept them in sync — a skill edited in one
// tree and not the other drifts silently, and the dogfooded agent then follows
// instructions the product never shipped. `.claude/skills/` is deliberately NOT
// compared: .gitignore excludes it, so it holds zero tracked files and is
// regenerated by `codument update` rather than edited.
const SHIPPED = "skills";
const TRACKED_MIRROR = join(".agents", "skills");

/** Every file under `root`, as paths relative to it, sorted. */
function filesUnder(root: string): string[] {
  const out: string[] = [];
  const walk = (dir: string) => {
    for (const entry of readdirSync(dir).sort()) {
      const abs = join(dir, entry);
      if (statSync(abs).isDirectory()) walk(abs);
      else out.push(relative(root, abs).split(sep).join("/"));
    }
  };
  walk(root);
  return out.sort();
}

describe("shipped skills and their tracked mirror stay identical", () => {
  it("both trees exist and are non-empty", () => {
    // Guards the comparisons below from passing vacuously if a tree is moved or
    // renamed — comparing two empty lists is trivially equal.
    assert.ok(existsSync(SHIPPED), `${SHIPPED}/ must exist`);
    assert.ok(existsSync(TRACKED_MIRROR), `${TRACKED_MIRROR}/ must exist`);
    assert.ok(filesUnder(SHIPPED).length > 0, `${SHIPPED}/ must not be empty`);
  });

  it("contain exactly the same set of files", () => {
    assert.deepEqual(
      filesUnder(TRACKED_MIRROR),
      filesUnder(SHIPPED),
      `${TRACKED_MIRROR}/ and ${SHIPPED}/ hold different files — a skill was added, ` +
        "removed, or renamed in one tree only.",
    );
  });

  it("every file is byte-identical across both trees", () => {
    const drifted: string[] = [];
    for (const rel of filesUnder(SHIPPED)) {
      const a = readFileSync(join(SHIPPED, rel), "utf-8");
      const b = readFileSync(join(TRACKED_MIRROR, rel), "utf-8");
      if (a !== b) drifted.push(rel);
    }
    assert.deepEqual(
      drifted,
      [],
      `edited in one tree only — copy ${SHIPPED}/<path> over ${TRACKED_MIRROR}/<path> ` +
        "(or re-run `codument update`, which rewrites the mirror and leaves a " +
        "SKILL.md.backup to delete): " + drifted.join(", "),
    );
  });
});
